# Generated by Django 5.2.13 on 2026-04-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzlehunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('scoring_type', models.CharField(choices=[('points', 'Points'), ('time', 'Time')], max_length=10)),
                ('hint1_min_minutes', models.PositiveIntegerField(default=0)),
                ('hint2_min_minutes', models.PositiveIntegerField(default=0)),
                ('hint3_min_minutes', models.PositiveIntegerField(default=0)),
                ('allow_skip', models.BooleanField(default=False)),
                ('show_total_count', models.BooleanField(default=True)),
                ('max_active_puzzles', models.PositiveIntegerField(blank=True, help_text='Maximum number of puzzles a team can have active (arrived but not solved/skipped) at the same time. Leave blank for no limit.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('arrival_code', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hint1_text', models.TextField(blank=True)),
                ('hint2_text', models.TextField(blank=True)),
                ('hint3_text', models.TextField(blank=True)),
                ('hint1_cost', models.PositiveIntegerField(default=0)),
                ('hint2_cost', models.PositiveIntegerField(default=0)),
                ('hint3_cost', models.PositiveIntegerField(default=0)),
                ('solve_message', models.TextField(blank=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='hunts.puzzle')),
                ('puzzlehunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='hunts.puzzlehunt')),
            ],
            options={
                'ordering': ['puzzlehunt', 'display_id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='accounts.team')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_attempts', to='hunts.puzzle')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('hints_taken', models.PositiveSmallIntegerField(default=0)),
                ('skipped', models.BooleanField(default=False)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='hunts.puzzle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to='accounts.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'puzzle'), name='unique_attempt_per_team_puzzle')],
            },
        ),
        migrations.AddConstraint(
            model_name='puzzle',
            constraint=models.UniqueConstraint(fields=('puzzlehunt', 'display_id'), name='unique_display_id_per_hunt'),
        ),
        migrations.AddConstraint(
            model_name='puzzle',
            constraint=models.UniqueConstraint(fields=('puzzlehunt', 'arrival_code'), name='unique_arrival_code_per_hunt'),
        ),
    ]
