# Generated by Django 5.2.13 on 2026-04-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(choices=[(1, '1st hint'), (2, '2nd hint'), (3, '3rd hint')])),
                ('text', models.TextField()),
                ('cost', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['puzzle', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['puzzlehunt', 'order', 'display_id']},
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hint1_cost',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hint1_text',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hint2_cost',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hint2_text',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hint3_cost',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hint3_text',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Numeric ordering within the hunt. Leave blank to auto-assign the lowest unused number.', null=True),
        ),
        migrations.AddConstraint(
            model_name='puzzle',
            constraint=models.UniqueConstraint(fields=('puzzlehunt', 'order'), name='unique_order_per_hunt'),
        ),
        migrations.AddField(
            model_name='hint',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='hunts.puzzle'),
        ),
        migrations.AddConstraint(
            model_name='hint',
            constraint=models.UniqueConstraint(fields=('puzzle', 'order'), name='unique_hint_order_per_puzzle'),
        ),
    ]
