# Generated by Django 5.2.13 on 2026-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_hint_alter_puzzle_options_remove_puzzle_hint1_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePuzzleAttempt',
            fields=[
            ],
            options={
                'verbose_name': 'active puzzle',
                'verbose_name_plural': 'active puzzles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hunts.puzzleattempt',),
        ),
        migrations.CreateModel(
            name='FinishedPuzzleAttempt',
            fields=[
            ],
            options={
                'verbose_name': 'finished puzzle',
                'verbose_name_plural': 'finished puzzles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hunts.puzzleattempt',),
        ),
    ]
