# Generated by Django 5.2.13 on 2026-04-26 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0003_activepuzzleattempt_finishedpuzzleattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('puzzlehunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='hunts.puzzlehunt')),
            ],
            options={
                'ordering': ['puzzlehunt', 'order', 'name'],
            },
        ),
    ]
