# Generated by Django 5.2.13 on 2026-04-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_puzzle_base_points_alter_contact_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='base_points',
            field=models.PositiveIntegerField(default=10, help_text='Points awarded for solving this puzzle (only used for points-based hunts).'),
        ),
    ]
