# Generated by Django 5.2.13 on 2026-04-27 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_team_options_alter_team_created_at_and_more'),
        ('hunts', '0006_alter_puzzle_base_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activepuzzleattempt',
            options={'verbose_name': 'aktivní šifra', 'verbose_name_plural': 'aktivní šifry'},
        ),
        migrations.AlterModelOptions(
            name='answerattempt',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'odpověď', 'verbose_name_plural': 'odpovědi'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['puzzlehunt', 'order', 'name'], 'verbose_name': 'kontakt', 'verbose_name_plural': 'kontakty'},
        ),
        migrations.AlterModelOptions(
            name='finishedpuzzleattempt',
            options={'verbose_name': 'dokončená šifra', 'verbose_name_plural': 'dokončené šifry'},
        ),
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['puzzle', 'order'], 'verbose_name': 'nápověda', 'verbose_name_plural': 'nápovědy'},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ['puzzlehunt', 'order', 'display_id'], 'verbose_name': 'šifra', 'verbose_name_plural': 'šifry'},
        ),
        migrations.AlterModelOptions(
            name='puzzleattempt',
            options={'verbose_name': 'pokus o šifru', 'verbose_name_plural': 'pokusy o šifry'},
        ),
        migrations.AlterModelOptions(
            name='puzzlehunt',
            options={'verbose_name': 'šifrovačka', 'verbose_name_plural': 'šifrovačky'},
        ),
        migrations.AlterField(
            model_name='answerattempt',
            name='correct',
            field=models.BooleanField(verbose_name='správně'),
        ),
        migrations.AlterField(
            model_name='answerattempt',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_attempts', to='hunts.puzzle', verbose_name='šifra'),
        ),
        migrations.AlterField(
            model_name='answerattempt',
            name='submitted_answer',
            field=models.CharField(max_length=200, verbose_name='odeslaná odpověď'),
        ),
        migrations.AlterField(
            model_name='answerattempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='odesláno'),
        ),
        migrations.AlterField(
            model_name='answerattempt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_attempts', to='accounts.team', verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='jméno'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='poznámka'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Pořadí zobrazení v rámci šifrovačky. Prázdné = automaticky doplnit nejnižší volné číslo.', null=True, verbose_name='pořadí'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=40, verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='puzzlehunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='hunts.puzzlehunt', verbose_name='šifrovačka'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='cena'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(1, '1. nápověda'), (2, '2. nápověda'), (3, '3. nápověda')], verbose_name='pořadí'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='hunts.puzzle', verbose_name='šifra'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='arrival_code',
            field=models.CharField(max_length=100, verbose_name='příchozí kód'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='base_points',
            field=models.PositiveIntegerField(default=10, help_text='Body udělené za vyřešení této šifry (používá se pouze u bodových šifrovaček).', verbose_name='základní body'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='display_id',
            field=models.CharField(max_length=20, verbose_name='identifikátor'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Číselné pořadí v rámci šifrovačky. Prázdné = automaticky doplnit nejnižší volné číslo.', null=True, verbose_name='pořadí'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='password',
            field=models.CharField(max_length=100, verbose_name='heslo'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='hunts.puzzle', verbose_name='předpoklady'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzlehunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='hunts.puzzlehunt', verbose_name='šifrovačka'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solve_message',
            field=models.TextField(blank=True, verbose_name='zpráva po vyřešení'),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='arrived_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='příchod'),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='hints_taken',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='použité nápovědy'),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='hunts.puzzle', verbose_name='šifra'),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='skipped',
            field=models.BooleanField(default=False, verbose_name='přeskočeno'),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vyřešeno'),
        ),
        migrations.AlterField(
            model_name='puzzleattempt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to='accounts.team', verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='allow_skip',
            field=models.BooleanField(default=False, verbose_name='povolit přeskočení'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='hint1_min_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='minuty do 1. nápovědy'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='hint2_min_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='minuty do 2. nápovědy'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='hint3_min_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='minuty do 3. nápovědy'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktivní'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='max_active_puzzles',
            field=models.PositiveIntegerField(blank=True, help_text='Nejvyšší počet šifer, které může mít tým otevřené (doražených, ale nevyřešených/nepřeskočených) zároveň. Prázdné = bez omezení.', null=True, verbose_name='max. počet aktivních šifer'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='scoring_type',
            field=models.CharField(choices=[('points', 'Body'), ('time', 'Čas')], max_length=10, verbose_name='typ bodování'),
        ),
        migrations.AlterField(
            model_name='puzzlehunt',
            name='show_total_count',
            field=models.BooleanField(default=True, verbose_name='zobrazit celkový počet šifer'),
        ),
    ]
