# Generated by Django 5.2.13 on 2026-05-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0007_alter_activepuzzleattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='arrival_message',
            field=models.TextField(blank=True, verbose_name='zpráva po doražení'),
        ),
    ]
