# Generated by Django 5.2.13 on 2026-04-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='puzzlehunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hunts.puzzlehunt'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('puzzlehunt', 'name'), name='unique_team_name_per_hunt'),
        ),
    ]
