# Generated by Django 5.2.13 on 2026-04-27 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('hunts', '0006_alter_puzzle_base_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['puzzlehunt', 'name'], 'verbose_name': 'tým', 'verbose_name_plural': 'týmy'},
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='název týmu'),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=128, verbose_name='heslo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='puzzlehunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hunts.puzzlehunt', verbose_name='šifrovačka'),
        ),
    ]
